// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Validate environment variables before creating client
const isValidConfig = SUPABASE_URL.length > 0 && SUPABASE_PUBLISHABLE_KEY.length > 0;

// Create client only if config is valid, otherwise create a placeholder
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

if (isValidConfig) {
  try {
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (error) {
    console.error('Failed to initialize Supabase client:', error);
    supabaseInstance = null;
  }
} else {
  console.warn('Supabase environment variables missing - app will run in demo mode');
}

// Export the client (or null if initialization failed)
export const supabase = supabaseInstance;