// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Validate environment variables before creating client
const isValidConfig = SUPABASE_URL.length > 0 && SUPABASE_PUBLISHABLE_KEY.length > 0;

// Log config status for debugging
console.log('[Supabase] URL set:', !!SUPABASE_URL);
console.log('[Supabase] Key set:', !!SUPABASE_PUBLISHABLE_KEY);

// Safe localStorage wrapper for mobile Safari Private Browsing compatibility
let safeStorage: Storage | null = null;
try {
  safeStorage = localStorage;
  // Test if localStorage actually works (mobile Safari may throw)
  safeStorage.setItem('__test__', 'test');
  safeStorage.removeItem('__test__');
} catch (e) {
  console.warn('[Supabase] localStorage unavailable (Private Browsing?), using memory fallback');
  safeStorage = null;
}

// Create client only if config is valid, otherwise create a placeholder
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

if (isValidConfig) {
  try {
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage || undefined,
        persistSession: safeStorage !== null,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    });
    console.log('[Supabase] Client created successfully');
  } catch (error) {
    console.error('[Supabase] Failed to initialize Supabase client:', error);
    supabaseInstance = null;
  }
} else {
  console.warn('[Supabase] Environment variables missing - app will run in demo mode');
}

// Export the client (or null if initialization failed)
export const supabase = supabaseInstance;